name: antojoscolombianos
favicon: null
layout_spectrum: 0.30962
typography_spectrum: 0.51109
title: Antojos Colombianos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffde00'
    - '#09428f'
    - '#ce181f'
    - '#8ea8cb'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
