name: antojoscolombianos
favicon: null
layout_spectrum: 0.30962
typography_spectrum: 0.51109
title: Antojos Colombianos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31459c'
    - '#ede810'
    - '#ee3a24'
    - '#000000'
    - '#7a7a4f'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
